### PR TITLE
Fix hardcoded comment types to support third-party plugins.

### LINKED ISSUE #1141: ActivityPub likes and reposts from Fediverse not displaying on event pages
### Describe the bug

When using GatherPress in conjunction with the ActivityPub plugin, likes and reposts (boosts) from Fediverse platforms (e.g., Mastodon, Pleroma) are not displayed on event pages, even though fediverse reactions are visible in the template. This issue persists despite the ActivityPub plugin's functionality to display such interactions on standard WordPress posts.
This might be related to this issue: [ActivityPub comments on GatherPress events not appearing in WordPress despite email notifications](https://github.com/Automattic/wordpress-activitypub/issues/2004)

**Expected Behavior**

Likes and reposts from Fediverse platforms should be displayed on the event page, similar to how they appear on standard WordPress posts when using the ActivityPub plugin.

**Actual Behavior**

Likes and reposts from Fediverse platforms do not appear on the event page.

**Additional Context**

This issue may be related to how GatherPress handles custom post types and their compatibility with the ActivityPub plugin's reactions feature. Notably, the Event Bridge for ActivityPub plugin, which integrates event plugins with ActivityPub, lists GatherPress as a supported event plugin. 

Could this issue be specific to GatherPress's implementation, or might it be a broader compatibility issue between custom post types and the ActivityPub plugin? 

### Steps to Reproduce

1. Ensure that the GatherPress and ActivityPub plugins are installed and activated on your WordPress site.
2. Create a new event using GatherPress.
3. From a Fediverse account, like or repost (boost) the shared event.
4. Return to the event page on your WordPress site and check for the display of the like or repost.

### Screenshots, screen recording, code snippet

_No response_

### Environment information

WordPress version: 6.8.2
Plugins and versions:
-  ActivityPub: 7.2.0
-  Event Bridge for ActivityPub: 1.1.1
-  GatherPress: 0.32.3

### WordPress information

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mauteri**
### Description of the Change
Fixes an issue where the RSVP query exclusion was hardcoding WordPress default comment types, which could cause conflicts with other
  plugins that register custom comment types.

  Changes:
  - Dynamic fetching of all comment types from the database
  - 24-hour transient caching for performance
  - Automatic cache invalidation when new comment types are detected
 
  This ensures GatherPress plays nicely with other plugins in the WordPress ecosystem.

Closes #1141

### Changelog Entry

> Fixed - Bug fix

### Credits

Props @mauteri

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/GatherPress/gatherpress/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

File: includes/core/classes/class-rsvp-query.php [hunk 1]
```diff
@@ -138,6 +138,44 @@ public function get_rsvp( array $args ): ?WP_Comment {
...
+				)
+			);
+
+			// If no types found, use WordPress defaults.
+			if ( empty( $types ) ) {
+				$types = array( 'comment', 'pingback', 'trackback' );
+			}
+
+			// Cache for 5 minutes.
+			set_transient( $cache_key, $types, 5 * MINUTE_IN_SECONDS );
```
Comment (mauteri) [inline includes/core/classes/class-rsvp-query.php]: Keep 24 hours and bust cache if a comment type doesn't exist in the cache.

Comment (mauteri) [reply includes/core/classes/class-rsvp-query.php]: Also link to trac ticket about indexing comment_type
