### PR TITLE
Move GP core function to init hook to fix translation error - Take two

### LINKED ISSUE #1021: Translation notice
### Describe the bug

Since I changed the site language to Dutch, I get the debug notice 'Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the gatherpress domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see Debugging in WordPress for more information. (This message was added in version 6.7.0.)'. 

### Steps to Reproduce

Set website to a default language that has translations like Dutch
Set debug to true
See the notice in admin and frontend

### Screenshots, screen recording, code snippet

_No response_

### Environment information

WP 6.7.2 
Dutch lang
GatherPress 0.31.0

### WordPress information

The problem is not the translation, I think. To me the problem seems to be that the function call 'GatherPress\Core\Setup::get_instance();' in gatherpress.php is executed straight away, on loading the file. This triggers the construct in class-settings.php. But the first method in the construct needs translation functionalities, which are not prepaired yet by WordPress. The second and third depend on the first. The solution that works for me is putting them in an init hook or admin_menu hook. I have not tested this to the max yet :-) 

	protected function __construct() {
		add_action( 'init', function () { //or admin_menu if only needed in admin
			$this->instantiate_classes(); // needs translation
			$this->set_current_page(); // depends on instantiate_classes()
			$this->set_main_sub_page(); // depends on instantiate_classes()
		});

		$this->setup_hooks();
	}

Another option might be to put GatherPress\Core\Setup::get_instance() in an init-hook with priority under 10.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jmarx**
### Description of the Change
Move sub pages core function to init hook to remove translations notice.

Closes #1021 

### How to test the Change
Switch your language setting to Dutch and turn on `debug` mode and ensure you don't get a notice about the translation functionality loading too late.

### Credits
Props @mauteri, @jmarx 

- [X] I agree to follow this project's [**Code of Conduct**](https://github.com/GatherPress/gatherpress/blob/main/CODE_OF_CONDUCT.md).
- [X] I have updated the documentation accordingly.
- [X] I have added tests to cover my change.
- [X] All new and existing tests pass.

### CODE REVIEW

File: includes/core/classes/settings/class-base.php [hunk 1]
```diff
@@ -121,6 +121,7 @@ protected function get_sections(): array {
 	 * @return void
 	 */
 	protected function setup_hooks(): void {
+		add_action( 'init', array( $this, 'set_main_sub_page' ) );
```
Comment (mauteri) [inline includes/core/classes/settings/class-base.php:124]: Why did you add this and the empty callbacks?

**Review by mauteri — CHANGES_REQUESTED** [review]

File: includes/core/classes/settings/class-base.php (hunk 1 above)
Comment (jmarx) [reply includes/core/classes/settings/class-base.php]: @mauteri Fixed

**Review by mauteri — APPROVED** [review]
