### PR TITLE
Fix .ics downloads with custom slugs, auto-flush rewrites on update, and add-to-calendar Query Loop context.

### LINKED ISSUE #1341: Add to Calendar: iCal / Outlook download returns 404 (Page Not Found)
### Describe the bug

When using the **Add to Calendar** option on a single event page, selecting **iCal** or **Outlook** results in a **404 / Page Not Found** response instead of downloading an `.ics` calendar file (or otherwise exporting the event).

### Steps to Reproduce

1. Create or open any single event page that includes the **Add to Calendar** UI.
2. Click **Add to calendar**.
3. Click **iCal**.
4. Observe the result.
5. Repeat steps 2–3 but click **Outlook**.

### Screenshots, screen recording, code snippet

This looks like the iCal/Outlook export endpoint (route/query var/rewrite rule) is not being resolved by WordPress, causing the request to fall through to the normal template loader and produce a 404.

#### Additional debugging info
- The exact iCal link URL being generated:
  - iCal URL: https://example.com/events/event.ics
  - Outlook URL: https://example.com/events/event.ics

### Environment information

- GatherPress version: 0.33.0
- WordPress version: 6.9
- Permalink structure: day and name
- Theme: twenty-twenty-five

### WordPress information

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mauteri**
### Description of the Change
  - Fix .ics download 404s when using custom event slugs (fixes #1341)
  - Add automatic rewrite rule flushing on plugin version updates
  - Fix add-to-calendar block context fallback for Query Loops
 

Closes #1341

### How to test the Change

  1. Test .ics Downloads with Default Slug

  - Create an event
  - Add .ics to the end of the event URL (e.g., yoursite.com/events/my-event.ics)
  - Verify the .ics file downloads successfully
  - Open the .ics file and verify it contains the event details

  2. Test .ics Downloads with Custom Slug

  - Go to Settings → General → URLs
  - Change the event slug from default to something else (e.g., veranstaltung or happenings)
  - Visit Settings → Permalinks and click "Save Changes" to flush rewrite rules
  - Create a new event
  - Add .ics to the event URL using the new slug (e.g., yoursite.com/veranstaltung/my-event.ics)
  - Verify the .ics file downloads successfully

  3. Test Automatic Rewrite Rule Flushing on Update

  - Check database for gatherpress_version option value (should match current plugin version)
  - Simulate a plugin update by changing the version in gatherpress_version option to 0.1.0
  - Visit any admin page to trigger admin_init hook
  - Check that gatherpress_version option is now updated to current version
  - Verify rewrite_rules option was deleted and regenerated

  4. Test Add-to-Calendar Block in Query Loop

  - Create a Query Loop block that displays events
  - Add the "Add to Calendar" block inside the Query Loop template
  - In Editor: Verify the block appears at full opacity (not semi-transparent)
  - On Frontend: Verify the calendar links work correctly for each event in the loop
  - Click a calendar link and verify it generates the correct .ics download for that specific event

  5. Test Add-to-Calendar Block Outside Query Loop

  - Add "Add to Calendar" block directly to an event post
  - Verify it works normally (no regression)

### Changelog Entry

> Fixed - Bug fix

### Credits

Props @mauteri 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/GatherPress/gatherpress/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by carstingaxion** [comment]
# Running Test 2

image

- [x]  `https://playground.wordpress.net/scope:curious-chic-lake/happenings/1-ics-test.ics`

**Review by jmarx — APPROVED** [review]
LGTM

File: includes/core/classes/class-event-setup.php [hunk 1]
```diff
@@ -327,16 +327,20 @@ public function register_post_meta(): void {
...
+	 * dynamically generated ICS files for individual events. The URL slug
+	 * matches the configured event post type slug from GatherPress settings.
 	 *
 	 * @since 1.0.0
 	 *
 	 * @return void
 	 */
 	public function register_calendar_rewrite_rule(): void {
+		$settings     = Settings::get_instance();
+		$rewrite_slug = sanitize_title( $settings->get_value( 'general', 'urls', 'events' ) );
```
Comment (jmarx) [inline includes/core/classes/class-event-setup.php:340]: Not a big deal. But let's add `events` as a default here?

Comment (mauteri) [reply includes/core/classes/class-event-setup.php:340]: Should be `event` I think, but point taken. Thanks!

Comment (mauteri) [reply includes/core/classes/class-event-setup.php:340]: This is actually not needed because `get_value` for this has a fallback to the default built in which is set in the configuration.
