### PR TITLE
Hide Admin Notice about alpha-plugin, also if installed via the branch-named zip

### LINKED ISSUE #807: seeing The GatherPress Alpha plugin notice
### Describe the bug

I am getting a notice in wp-admin  and wp-admin/network saying:

The GatherPress Alpha plugin is not installed or activated. This plugin is currently in heavy development and requires GatherPress Alpha to handle breaking changes. Please [download and install GatherPress Alpha](https://github.com/GatherPress/gatherpress-alpha) to ensure compatibility and avoid issues.

But as per the screenshot below both are activated (network activated infact). Maybe this is because I am using multisite. If so this needs to be corrected

Screenshot from 2024-08-16 19-39-12

### Steps to Reproduce

Network activate both GatherPress and GatherPress Alpha Version 0.30.0 on  multisite

### Screenshots, screen recording, code snippet

Screenshot from 2024-08-16 19-39-12

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by carstingaxion**
While a plugin from w.org would have a unigue slug to check against,
this is different for .zips downloaded from github.com.

A download via "<> Code ⏷" > "Download ZIP" will include the branch in the file name,
while a download via "Releases" will provide a zip without a branch name attached.

### Description of the Change

This PR makes sure, that GatherPress checks against both possible slugs inside the condition to whether or not to show the admin notice about the alpha-plugin.

Closes #807

### Changelog Entry

> Fixed - Hide Admin Notice about alpha-plugin, also if installed via the branch-named zip

### Credits

Props @carstingaxion 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/GatherPress/gatherpress/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

File: includes/core/classes/class-setup.php [hunk 1]
```diff
@@ -432,6 +432,11 @@ public function check_users_can_register(): void {
 	 */
 	public function check_gatherpress_alpha(): void {
 		if (
+			// While a plugin from w.org would have a unigue slug to check against,
+			// it different for .zips downloaded from github.com.
+			// A download via "<> Code ⏷" > "Download ZIP" will include the branch in the file name.
+			is_plugin_active( 'gatherpress-alpha-main/gatherpress-alpha.php' ) ||
+			// A download via "Releases" will provide a zip without a branch name attached.
```
Comment (mauteri) [inline includes/core/classes/class-setup.php:439]: Might be better to change this to see if the GatherPress Alpha version constant is defined, then we don't have to worry about file name.

Comment (carstingaxion) [reply includes/core/classes/class-setup.php:439]: Good idea.

**Comment by carstingaxion** [comment]
Friendly ping @mauteri ;)

**Review by mauteri — APPROVED** [review]
